# SCREEN
SCREEN_WIDTH = 1280 # Default: 1280
SCREEN_HEIGHT = 980 # Default: 980
# PLAYER
PLAYER_HEALTH = 3 # Default: 3
PLAYER_SPEED = 200 # Default: 200
PLAYER_TURN_SPEED = 300 # Default: 300
PLAYER_RADIUS = 20 # Default 20
PLAYER_SHOOT_SPEED = 500 # Default: 500
PLAYER_SHOOT_COOLDOWN = 0.3 # Default: 0.3
PLAYER_SUPER_SHOT_COOLDOWN = 2  # Default: 2
# BULLETS
SHOT_RADIUS = 5 # Default: 5
SUPER_SHOT_RADIUS = 4 # Default: 4
SUPER_SHOT_PELLETS = 10 # Default: 10
# ASTEROIDS
ASTEROID_MIN_RADIUS = 20 # Default: 20
ASTEROID_KINDS = 3 # Default: 3
ASTEROID_SPAWN_RATE = 0.8 # seconds Default: 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS # Do not change
# IMAGES
SPACE_BACKGROUND = "./images/space_background.jpg"