# SCREEN
SCREEN_WIDTH = 1732
SCREEN_HEIGHT = 964
# PLAYER
PLAYER_HEALTH = 3 # Default: 3
PLAYER_SPEED = 200 # Default: 200
PLAYER_TURN_SPEED = 300 # Default: 300
PLAYER_RADIUS = 20 # Default 20
PLAYER_SHOOT_SPEED = 500 # Default: 500
PLAYER_SHOOT_COOLDOWN = 0.3 # Default: 0.3
PLAYER_SUPER_SHOT_COOLDOWN = 2  # Default: 2
# BULLETS
SHOT_RADIUS = 5
SUPER_SHOT_RADIUS = 4
# ASTEROIDS
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
# IMAGES
SPACE_BACKGROUND = "./images/space_background.jpg"